### ISSUE TITLE
Псевдоклассы и селектор :host

### ISSUE THREAD

**Issue by vitkarpov** [stylobate/stylobate#87]
Используя stylobate для реализации островного дизайна в библиотеке веб-компонентов.

Например, есть такой styl-код:

```
:host
  kind: button
```

После компиляции получаем цсс:

```
:host:active
  ...

:host:hover
  ...

:host:hover:before
  ...
```

Это не работает, потому что псевдоклассы должны оборачиваться в скобочки при использовании вместе с `:host`

```
:host(:active)
  ...

:host(:hover):before
  ...
```

Имеет ли смысл поддерживать это на стороне `stylobate` или лучше постпроцессить цсс на стороне моего сборщика, после компиляции стилусом?

**Comment by kizu** [comment]
Нет никаких проблем сделать такой плагин к стайлусу на postcss, который будет править все такие селекторы (в рамках самого стайлуса это точно лучше не делать), но надо подумать нужно ли включать этот плагин прямо в стилобат, или же, действительно, снаружи использовать.

**Comment by vitkarpov** [comment]
Ага, понял. Я так и подумал, спасибо. В подтверждении моих мыслей просто.
